package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestRealCaptureOracles compares the fake's output against
// testdata/real-captures/*.json: immutable reference envelopes, NOT regular
// goldens. Unlike checkGolden (used by TestGoldenEnvelopes), this test never
// writes these files — there is no -update path here on purpose. If a fixture
// or code change makes an assertion below fail, that is a signal the
// envelope's contract shape actually changed; verify the new shape against
// the sibling tinvest repo's internal/render field order (see README.md) and
// hand-edit the reference file deliberately, rather than regenerating it from
// the fake. See README.md "Real-capture oracles" for what backs each file.
func TestRealCaptureOracles(t *testing.T) {
	t.Run("version", func(t *testing.T) {
		// This scenario pins version/go_version to the exact strings a real
		// `tinvest version -o json` run reported (see README.md), so the fake's
		// output is byte-identical to real-captures/version.json — the one
		// command in this fixture set that is a literal, unmodified real
		// capture rather than a hand-sanitized reconstruction.
		dir := t.TempDir()
		writeFile(t, filepath.Join(dir, "scenario.toml"), `
version = "0.0.0-SNAPSHOT-4552740"
go_version = "go1.26.5"
`)
		_, out := invoke(t, map[string]string{"FAKETINVEST_SCENARIO": dir}, "version", "-o", "json")
		assertMatchesCapture(t, "version.json", out)
	})

	t.Run("instruments_get", func(t *testing.T) {
		_, out := invoke(t, map[string]string{"FAKETINVEST_SCENARIO": happyDir},
			"instruments", "get", "SBER@TQBR", "-o", "json")
		assertMatchesCapture(t, "instruments_get.json", out)
	})

	t.Run("orders_place", func(t *testing.T) {
		_, out := invoke(t, map[string]string{"FAKETINVEST_SCENARIO": happyDir},
			"orders", "place", "--instrument", "SBER@TQBR", "--direction", "buy", "--quantity", "1",
			"--type", "limit", "--price", "270.5", "--order-id", orderUUID1, "-o", "json")
		assertMatchesCapture(t, "orders_place.json", out)
	})
}

func assertMatchesCapture(t *testing.T, name, got string) {
	t.Helper()
	path := filepath.Join("testdata", "real-captures", name)
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read real-capture oracle %s: %v", path, err)
	}
	if strings.TrimRight(string(want), "\n") != strings.TrimRight(got, "\n") {
		t.Errorf("output drifted from the real-capture oracle %s (hand-maintained, not regenerated by -update)\n--- want ---\n%s\n--- got ---\n%s", path, want, got)
	}
}
